services:
  web-api:
    image: aoirint/aoirint_mcping_server_web_api:0.1.6
    restart: always
    environment:
      - MCPING_WEB_API_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres
      - MCPING_WEB_API_READ_API_KEY=${MCPING_WEB_API_READ_API_KEY:?}
      - MCPING_WEB_API_WRITE_API_KEY=${MCPING_WEB_API_WRITE_API_KEY:?}
    depends_on:
      - postgres

  bedrock-updater:
    image: aoirint/aoirint_mcping_server_bedrock_updater:0.1.6
    restart: always
    environment:
      - MCPING_BEDROCK_UPDATER_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres
      - MCPING_BEDROCK_UPDATER_INTERVAL=${MCPING_BEDROCK_UPDATER_INTERVAL:?}
    depends_on:
      - postgres

  java-updater:
    image: aoirint/aoirint_mcping_server_java_updater:0.1.6
    restart: always
    environment:
      - MCPING_JAVA_UPDATER_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres
      - MCPING_JAVA_UPDATER_INTERVAL=${MCPING_JAVA_UPDATER_INTERVAL:?}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - "${POSTGRES_DATA_ROOT:?}:/var/lib/postgresql/data"

  migrate:
    image: migrate/migrate:v4.16.2
    command: "migrate version"
    volumes:
      - "./migrations:/migrations"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web-api
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN:?}

  # (Optional) adminer: Browser database management
  # adminer:
  #   image: adminer:4.8.1
  #   restart: always
  #   ports:
  #     - "${ADMINER_HOST_PORT:?}:8080"
  #   depends_on:
  #     - postgres
